// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: main.proto
// Protobuf Java Version: 4.31.1

package io.github.secretumchat.secretum.proto;

@com.google.protobuf.Generated
public final class Main {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_secretum_proto_Empty_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_secretum_proto_Empty_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 31,
                /* patch= */ 1,
                /* suffix= */ "",
                Main.class.getName());
    }

    static {
        java.lang.String[] descriptorData = {
                "\n\nmain.proto\022\016secretum.proto\"\007\n\005Empty2<\n" +
                        "\004Test\0224\n\004Test\022\025.secretum.proto.Empty\032\025.s" +
                        "ecretum.proto.EmptyB7\n%io.github.secretu" +
                        "mchat.secretum.protoZ\016secretum/protob\006pr" +
                        "oto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_secretum_proto_Empty_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_secretum_proto_Empty_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_secretum_proto_Empty_descriptor,
                new java.lang.String[]{});
        descriptor.resolveAllFeaturesImmutable();
    }

    private Main() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface EmptyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:secretum.proto.Empty)
            com.google.protobuf.MessageOrBuilder {
    }

    /**
     * Protobuf type {@code secretum.proto.Empty}
     */
    public static final class Empty extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:secretum.proto.Empty)
            EmptyOrBuilder {
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:secretum.proto.Empty)
        private static final io.github.secretumchat.secretum.proto.Main.Empty DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Empty>
                PARSER = new com.google.protobuf.AbstractParser<Empty>() {
            @java.lang.Override
            public Empty parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 31,
                    /* patch= */ 1,
                    /* suffix= */ "",
                    Empty.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new io.github.secretumchat.secretum.proto.Main.Empty();
        }

        private byte memoizedIsInitialized = -1;

        // Use Empty.newBuilder() to construct.
        private Empty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Empty() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.github.secretumchat.secretum.proto.Main.internal_static_secretum_proto_Empty_descriptor;
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.github.secretumchat.secretum.proto.Main.Empty prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static io.github.secretumchat.secretum.proto.Main.Empty getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Empty> parser() {
            return PARSER;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.github.secretumchat.secretum.proto.Main.internal_static_secretum_proto_Empty_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.github.secretumchat.secretum.proto.Main.Empty.class, io.github.secretumchat.secretum.proto.Main.Empty.Builder.class);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.github.secretumchat.secretum.proto.Main.Empty)) {
                return super.equals(obj);
            }
            io.github.secretumchat.secretum.proto.Main.Empty other = (io.github.secretumchat.secretum.proto.Main.Empty) obj;

            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Empty> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.github.secretumchat.secretum.proto.Main.Empty getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code secretum.proto.Empty}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:secretum.proto.Empty)
                io.github.secretumchat.secretum.proto.Main.EmptyOrBuilder {
            // Construct using io.github.secretumchat.secretum.proto.Main.Empty.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.github.secretumchat.secretum.proto.Main.internal_static_secretum_proto_Empty_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.github.secretumchat.secretum.proto.Main.internal_static_secretum_proto_Empty_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.github.secretumchat.secretum.proto.Main.Empty.class, io.github.secretumchat.secretum.proto.Main.Empty.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.github.secretumchat.secretum.proto.Main.internal_static_secretum_proto_Empty_descriptor;
            }

            @java.lang.Override
            public io.github.secretumchat.secretum.proto.Main.Empty getDefaultInstanceForType() {
                return io.github.secretumchat.secretum.proto.Main.Empty.getDefaultInstance();
            }

            @java.lang.Override
            public io.github.secretumchat.secretum.proto.Main.Empty build() {
                io.github.secretumchat.secretum.proto.Main.Empty result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.github.secretumchat.secretum.proto.Main.Empty buildPartial() {
                io.github.secretumchat.secretum.proto.Main.Empty result = new io.github.secretumchat.secretum.proto.Main.Empty(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.github.secretumchat.secretum.proto.Main.Empty) {
                    return mergeFrom((io.github.secretumchat.secretum.proto.Main.Empty) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.github.secretumchat.secretum.proto.Main.Empty other) {
                if (other == io.github.secretumchat.secretum.proto.Main.Empty.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            // @@protoc_insertion_point(builder_scope:secretum.proto.Empty)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
