// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: main.proto
//
package io.github.secretumchat.secretum.proto

import com.connectrpc.*

public class TestClient(
    private val client: ProtocolClientInterface,
) : TestClientInterface {
    override suspend fun test(request: Main.Empty, headers: Headers): ResponseMessage<Main.Empty> = client.unary(
        request,
        headers,
        MethodSpec(
            "secretum.proto.Test/Test",
            io.github.secretumchat.secretum.proto.Main.Empty::class,
            io.github.secretumchat.secretum.proto.Main.Empty::class,
            StreamType.UNARY,
        ),
    )

}
