// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: main.proto
//
package io.github.secretumchat.secretum.proto

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

public interface TestClientInterface {
    public suspend fun test(request: Main.Empty, headers: Headers = emptyMap()): ResponseMessage<Main.Empty>
}
